proyectoPrueba/gestionTareas/urls.py
from django.urls import path
from . import views

app_name="gestionTareas"
urlpatterns = [
	path("<int:usuario_id>", views.gestionTareas, name="gestionTareas"),

	
]

proyectoPrueba/main/urls.py
from django.urls import path
from . import views

app_name="pagina"
urlpatterns = [
	#localhost:8000/pagina
	path("", views.home, name="home"),
]

proyectoPrueba/pagina/urls.py
from django.urls import path
from . import views

app_name="pagina"
urlpatterns = [
	#localhost:8000/pagina
	path("", views.index, name="index"),
	#localhost:8000/pagina/
	path("todosLosUsuarios", views.todosLosUsuarios, name="todosLosUsuarios"),
	path("registrarse", views.vistaRegistroUsuario, name="registrarse"),
	path('registrarUsuario', views.registrarUsuario, name="registrarUsuario"),
	path('resultado', views.resultadoRegistro, name="resultadoRegistro" ),
	path('validacionExistenteUsuario', views.validacionExistenteUsuario, name="validacionExistenteUsuario")
]

proyectoPrueba/proyectoPrueba/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagina.urls')),
    path('gestionTareas/', include('gestionTareas.urls')),
]

proyectoPrueba/gestionTareas/models.py
from django.db import models

# Create your models here.

proyectoPrueba/pagina/models.py
from django.db import models

# Create your models here.


#Relacion 1 a muchos

class Usuario( models.Model ):
	nombre = models.CharField( max_length = 50 )
	contrasenia = models.CharField( max_length = 15 )
	dia_registro = models.DateTimeField("Dia registro")

	def __str__(self):
		return self.nombre


class Tarea( models.Model ):
	usuario = models.ForeignKey( Usuario, on_delete=models.CASCADE )
	nombreTarea = models.CharField( max_length = 60)
	estado = models.BooleanField( default = False )
	inicio = models.DateTimeField('Dia de inicio')
	finalizar = models.DateTimeField('Plazo maximo')

	def __str__(self):
		return self.nombreTarea

proyectoPrueba/gestionTareas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from pagina.models import Usuario, Tarea
from django.utils import timezone
# Create your views here.


def gestionTareas( request, usuario_id ):
	usuario = Usuario.objects.get( pk=usuario_id)

	if request.method == 'POST' and request.POST['nuevaTarea'] != '':


		nuevaTarea = request.POST['nuevaTarea']
		usuario.tarea_set.create(
				nombreTarea=nuevaTarea,
				inicio = timezone.now(),
				finalizar = timezone.now(),
			)

	return render( request, 'gestionTareas/index.html', {
				'usuario': usuario
			})

proyectoPrueba/main/views.py
from django.shortcuts import render

# Create your views here.


def home( request ):
	return render( request, 'main/home.html')

def gestionTareas( request ):
	return 

proyectoPrueba/pagina/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Usuario
from django.utils import timezone
from django.urls import reverse

def index( request ):
	usuarios = Usuario.objects.all()
	return render( request, 'pagina/index.html')

def todosLosUsuarios( request ):
	usuarios = Usuario.objects.all()

	return render( request, 'pagina/todosLosUsuarios.html',{
			'usuarios': usuarios
		})

def registrarUsuario( request ):
	try:
		nombre = request.POST['nombre']
		contrasenia = request.POST['contrasenia']
		dia_registro = timezone.now()
	except:
		return HttpResponse("Error")
	else:
		Usuario( nombre=nombre, contrasenia=contrasenia, dia_registro=dia_registro  ).save()
		return 	HttpResponseRedirect( reverse( "pagina:resultadoRegistro" ) )

def vistaRegistroUsuario( request ):
	return render( request, 'pagina/registrarse.html')

def resultadoRegistro( request ):
	return render( request, 'pagina/resultadoDelRegistro.html')

def validacionExistenteUsuario( request ):
	try:
		nombre = request.POST['nombreUsuario']
		contrasenia = request.POST['contraseniaUsuario']
		usuarioValidar = Usuario.objects.get(nombre=nombre)

	except :
		return render( request, 'pagina/index.html', {
			'error': 'Usuario no encontrado'
			})
	else:
		if( contrasenia == usuarioValidar.contrasenia ):
			return HttpResponseRedirect( reverse( 'gestionTareas:gestionTareas',
										  args=(usuarioValidar.id,)  ) )
		else:
			return render( request, 'pagina/index.html', {
					'error': 'Usuario o contrasenia no coincidentes'
				})

			# return HttpResponseRedirect( reverse( 'pagina:gestionTareas', args=(usuarioValidar.id) ) ) 

proyectoPrueba/gestionTareas/templates/gestionTareas/index.html
{% load static %}
<link rel="stylesheet"  href="{% static 'gestionTareas/style.css' %}">

<header>
	<h1>Hola {{usuario.nombre}}</h1>
</header>
<main>
	<section>
		<form action="" method="post">
			{% csrf_token %}
			<input type="text" name="nuevaTarea" placeholder="Ingresar nueva tarea" required>
			<input type="submit" valor="Agregar tarea">
		</form>
	</section>
	<section>
		<ul>
			{% for tarea in usuario.tarea_set.all %}
				<li>

					<h3>{{ tarea.nombreTarea}} </h3> 
					<button>Completada</button>
					<button>Eliminar</button> 
				
				</li>				
			{% endfor %}
		</ul>
	</section>
</main>

proyectoPrueba/main/templates/main/home.html
<header>
	<h1>Home</h1>
	<a href="{% url 'pagina:index' %}"><button>Iniciar sesion</button></a>
	<a href="{% url 'pagina:registrarse' %}"><button>Registrarse</button></a>
</header>

proyectoPrueba/pagina/templates/pagina/index.html
<main>
	<h1>Inicio sesion</h1>
	<section>
		{% if error %}
			<h2 style="color: red">{{ error }}</h2>
		{% endif %}


		<form action=" {% url 'pagina:validacionExistenteUsuario' %} " method="post">
			{% csrf_token %}
			<input type="text" name="nombreUsuario" required>
			<input type="password" name="contraseniaUsuario" required>
			<input type="submit" value="Ingresar">
		</form>
		<a href=" {% url 'pagina:registrarse' %}"><button>Registrarse</button></a>
	</section>
</main>

proyectoPrueba/pagina/templates/pagina/registrarse.html
<form action="{% url 'pagina:registrarUsuario' %}" method="post">
	{% csrf_token %}
	<fieldset>
		<h1>Registrar usuario</h1>
		<input type="text" name="nombre"  placeholder="nombre" required>
		<input type="password" name="contrasenia"  placeholder="contrasenia" required>
	</fieldset>
	<input type="submit" valor="enviar">
</form>

proyectoPrueba/pagina/templates/pagina/resultadoDelRegistro.html
<h1>Registro exitoso</h1>

<a href=" {% url 'pagina:index' %} "><button>Regresar al index</button></a> 

proyectoPrueba/pagina/templates/pagina/todosLosUsuarios.html
<main>
	<h1>Usuarios</h1>
	{% if usuarios %}
		<h2>Existen usuarios</h2>
		<ul>
			
			{% for usuario in usuarios%}
				<li> {{ usuario.nombre }} - {{ usuario.edad }} </li>
			{% endfor %}
		
		</ul>
	{% endif %}

</main>